/* eslint-disable @typescript-eslint/no-explicit-any */
'use strict';

import { Router, type Request, type Response } from 'express';
import { db } from '../db';
import { integrationApps, userIntegrations } from '@shared/schema';
import { and, eq } from 'drizzle-orm';
import { awsBedrockService } from '../services/aws-bedrock';
import { n8nService } from '../services/n8n';
import {
  compileConciergeRecipeToWorkflow,
  type ConciergeRecipe as CompilerConciergeRecipe,
} from '../services/integration-recipe-compiler';
import { storage } from '../storage';
import crypto from 'crypto';
import {
  WEBHOOK_PAYLOAD_SCHEMA_FOR_PROMPT,
  CONCIERGE_ALLOWED_TRIGGER_EVENTS,
  validateConciergeRecipe,
} from '../constants/platform-webhook-events';
import { seedIntegrationApps } from '../seed-integration-apps';

const chatRateLimit = new Map<string, number[]>();
function isRateLimited(key: string, limit: number, windowMs: number): { limited: boolean; retryAfterMs: number } {
  const now = Date.now();
  const windowStart = now - windowMs;
  const hits = (chatRateLimit.get(key) || []).filter((t) => t > windowStart);
  if (hits.length >= limit) {
    const oldest = hits[0];
    const retryAfterMs = Math.max(250, oldest + windowMs - now);
    chatRateLimit.set(key, hits);
    return { limited: true, retryAfterMs };
  }
  hits.push(now);
  chatRateLimit.set(key, hits);
  return { limited: false, retryAfterMs: 0 };
}

interface AuthRequest extends Request {
  userId?: string;
  isTeamMember?: boolean;
  teamMember?: { userId: string };
}

function getUserId(req: AuthRequest): string {
  if (req.isTeamMember && req.teamMember) return req.teamMember.userId;
  return req.userId || '';
}

type ConciergeQuestion = {
  id: string;
  prompt: string;
  inputType: 'text' | 'select';
  options?: Array<{ id: string; label: string }>;
};

// Mirror of the wider compiler ConciergeRecipe type so the route accepts both
// native (zendesk/slack/hubspot) and generic-HTTP recipes generated by the
// new wizard.
type ConciergeRecipe = CompilerConciergeRecipe;

function safeJsonParse<T>(raw: string): T | null {
  try {
    const match = raw.match(/\{[\s\S]*\}/);
    if (!match) return null;
    return JSON.parse(match[0]) as T;
  } catch {
    return null;
  }
}

async function bedrockConciergeChat(input: {
  message: string;
  context?: Record<string, any>;
}): Promise<
  | { type: 'questions'; questions: ConciergeQuestion[] }
  | { type: 'recipe'; recipe: ConciergeRecipe }
> {
  const fallbackFromMessage = (): { type: 'questions'; questions: ConciergeQuestion[] } | { type: 'recipe'; recipe: ConciergeRecipe } => {
    const msg = input.message || '';

    const triggerEvent =
      /ivr|menu|department|press \d|dtmf/i.test(msg) ? 'ivr.option_selected'
      : /inbound|ring|caller|first leg/i.test(msg) ? 'inbound_call.received'
      : /appointment/i.test(msg) ? 'appointment.booked'
      : /lead|contact/i.test(msg) ? 'lead.captured'
      : /campaign/i.test(msg) ? 'campaign.completed'
      : 'call.completed';

    if (/zendesk/i.test(msg)) {
      return {
        type: 'questions',
        questions: [
          { id: 'zendeskSubdomain', prompt: 'Zendesk subdomain (e.g. "acme" for acme.zendesk.com).', inputType: 'text' },
          { id: 'zendeskEmail', prompt: 'Zendesk agent email (for API token auth).', inputType: 'text' },
          { id: 'zendeskApiToken', prompt: 'Zendesk API token.', inputType: 'text' },
        ],
      };
    }

    if (/slack/i.test(msg)) {
      return {
        type: 'questions',
        questions: [
          { id: 'slackBotToken', prompt: 'Slack bot token (xoxb-...).', inputType: 'text' },
          { id: 'slackChannel', prompt: 'Slack channel (e.g. #support).', inputType: 'text' },
        ],
      };
    }

    if (/hubspot/i.test(msg)) {
      return {
        type: 'questions',
        questions: [
          { id: 'hubspotToken', prompt: 'HubSpot private app token.', inputType: 'text' },
        ],
      };
    }

    return {
      type: 'questions',
      questions: [
        {
          id: 'destination',
          prompt: `Which destination should we connect for "${triggerEvent}"?`,
          inputType: 'select',
          options: [
            { id: 'zendesk', label: 'Zendesk (create ticket)' },
            { id: 'slack', label: 'Slack (post message)' },
            { id: 'hubspot', label: 'HubSpot (create contact)' },
          ],
        },
      ],
    };
  };

  // Fallback: deterministic prompt-less behavior when Bedrock is not configured.
  if (!awsBedrockService.isConfigured()) {
    return fallbackFromMessage();
  }

  const allowedTriggers = CONCIERGE_ALLOWED_TRIGGER_EVENTS.join('","');
  const systemPrompt = [
    'You are an integrations concierge for a SaaS app that provisions n8n workflows.',
    'IMPORTANT: This app is an AI agent platform. Integrations start from PLATFORM EVENTS and send data to external services.',
    'Return ONLY valid JSON (no markdown).',
    'You must output one of:',
    '1) {"type":"questions","questions":[{"id":"...","prompt":"...","inputType":"text|select","options":[{"id":"...","label":"..."}]}]}',
    '2) {"type":"recipe","recipe":{...}}',
    'Recipe schema:',
    '- version: 1',
    `- name: string`,
    `- triggerEvent: one of ["${allowedTriggers}"]`,
    '- destination.slug: one of ["zendesk","slack","hubspot"]',
    '- intent: "platform_event_to_external_action"',
    '- destination.subdomain: required ONLY when destination.slug is zendesk (Zendesk subdomain, no .zendesk.com)',
    '- mapping: optional JSON for message/ticket fields',
    '- credentialsRequired: array of objects describing required credentials fields.',
    'Ask minimal questions if required fields are missing.',
    'Inbound automation examples:',
    '- "When an inbound call arrives" → triggerEvent inbound_call.received',
    '- "When caller picks sales from IVR" → triggerEvent ivr.option_selected (payload includes departmentId, departmentLabel, dtmf)',
    '- "When inbound call ends" → inbound_call.completed or call.completed depending on whether user said inbound specifically.',
    WEBHOOK_PAYLOAD_SCHEMA_FOR_PROMPT,
  ].join('\n');

  const userContent = JSON.stringify({
    message: input.message,
    context: input.context || {},
    examples: [
      'User: "When call is completed, create Zendesk ticket"',
      'Recipe: triggerEvent="call.completed", destination.slug="zendesk". Ask for zendeskSubdomain, zendeskEmail, zendeskApiToken.',
      'User: "Post call summary to Slack channel"',
      'Recipe: triggerEvent="call.completed", destination.slug="slack". Ask for slackBotToken and slackChannel.',
      'User: "When someone chooses billing from the phone menu, Slack #billing"',
      'Recipe: triggerEvent="ivr.option_selected", destination.slug="slack".',
    ],
  });

  let respText = '';
  try {
    const resp = await awsBedrockService.invoke({
      model: 'claude-sonnet-4-6',
      systemPrompt,
      messages: [{ role: 'user', content: userContent }],
      maxTokens: 1200,
      temperature: 0.2,
    });
    respText = resp.content;
  } catch (err: any) {
    console.warn('[Concierge] Bedrock invoke failed, falling back:', err?.message || err);
    return fallbackFromMessage();
  }

  const parsed = safeJsonParse<any>(respText);
  if (!parsed?.type) {
    console.warn('[Concierge] AI response not valid JSON, falling back');
    return fallbackFromMessage();
  }

  if (parsed.type === 'questions' && Array.isArray(parsed.questions)) {
    return { type: 'questions', questions: parsed.questions };
  }
  if (parsed.type === 'recipe' && parsed.recipe) {
    const recipe = parsed.recipe as ConciergeRecipe;
    const check = validateConciergeRecipe(recipe);
    if (!check.ok) {
      console.warn('[Concierge] Recipe failed validation:', check.error);
      return fallbackFromMessage();
    }
    return { type: 'recipe', recipe };
  }

  console.warn('[Concierge] AI response shape mismatch, falling back');
  return fallbackFromMessage();
}

export function createIntegrationConciergeRoutes() {
  const router = Router();

  router.get('/concierge/ping', async (req: AuthRequest, res: Response) => {
    const userId = getUserId(req);
    return res.json({ ok: true, userIdPresent: !!userId });
  });

  router.post('/concierge/chat', async (req: AuthRequest, res: Response) => {
    try {
      const userId = getUserId(req);
      if (!userId) return res.status(401).json({ error: 'Not authenticated' });

      const rl = isRateLimited(`chat:${userId}`, 5, 10_000);
      if (rl.limited) {
        res.setHeader('Retry-After', Math.ceil(rl.retryAfterMs / 1000));
        return res.status(429).json({ error: `Too many requests. Try again in ${Math.ceil(rl.retryAfterMs / 1000)}s.` });
      }

      const message = String(req.body?.message || '').trim();
      const context = req.body?.context || {};
      if (!message) return res.status(400).json({ error: 'Missing message' });

      const result = await bedrockConciergeChat({ message, context });
      return res.json(result);
    } catch (error: any) {
      return res.status(500).json({ error: error.message || 'Failed to chat' });
    }
  });

  router.post('/concierge/provision', async (req: AuthRequest, res: Response) => {
    try {
      const userId = getUserId(req);
      if (!userId) return res.status(401).json({ error: 'Not authenticated' });

      const recipe: ConciergeRecipe | undefined = req.body?.recipe;
      const inputs = req.body?.inputs || {};
      if (!recipe) return res.status(400).json({ error: 'Missing recipe' });

      const validation = validateConciergeRecipe(recipe);
      if (!validation.ok) {
        return res.status(400).json({ error: validation.error });
      }

      const destinationSlug = String(recipe.destination?.slug || '').trim();
      if (!destinationSlug) return res.status(400).json({ error: 'Missing recipe.destination.slug' });

      // Store linkage against the destination integration app.
      let [destinationApp] = await db
        .select()
        .from(integrationApps)
        .where(eq(integrationApps.slug, destinationSlug))
        .limit(1);

      if (!destinationApp) {
        await seedIntegrationApps();
        [destinationApp] = await db
          .select()
          .from(integrationApps)
          .where(eq(integrationApps.slug, destinationSlug))
          .limit(1);
      }

      if (!destinationApp) {
        return res.status(500).json({ error: `Integration app "${destinationSlug}" is not seeded in DB.` });
      }

      const existing = await db
        .select()
        .from(userIntegrations)
        .where(and(eq(userIntegrations.userId, userId), eq(userIntegrations.appId, destinationApp.id)))
        .limit(1);

      if (existing.length > 0) {
        return res.status(409).json({
          error: `An active ${destinationSlug} integration already exists. Disconnect it in Integrations or use a different destination.`,
        });
      }

      if (n8nService.isLocalMode()) {
        return res.status(500).json({ error: 'n8n is not configured (local mode). Set N8N_BASE_URL and N8N_API_KEY.' });
      }

      const compiled = await compileConciergeRecipeToWorkflow({
        userId,
        recipe,
        inputs,
      });

      // Subscribe the platform webhook event → n8n webhook URL
      const triggerEvent = String(recipe.triggerEvent || '').trim();
      if (!triggerEvent) {
        return res.status(400).json({ error: 'Missing recipe.triggerEvent' });
      }

      const webhookSecret = crypto.randomBytes(32).toString('hex');
      const platformWebhook = await storage.createWebhook({
        userId,
        name: `n8n (${recipe.destination.slug}) — ${triggerEvent}`,
        description: `Auto-created by Concierge for ${recipe.destination.slug}`,
        url: compiled.webhookUrl,
        method: 'POST',
        secret: webhookSecret,
        events: [triggerEvent],
        campaignIds: null,
        authType: null,
        authCredentials: null,
        headers: null,
        isActive: true,
      } as any);

      const [integration] = await db
        .insert(userIntegrations)
        .values({
          userId,
          appId: destinationApp.id,
          n8nWorkflowId: compiled.workflowId,
          n8nCredentialId: compiled.primaryCredentialId,
          webhookUrl: compiled.webhookUrl,
          status: 'active',
          config: {
            conciergeRecipe: recipe,
            destination: recipe.destination,
            n8n: {
              workflowName: compiled.workflowName,
              credentialIds: compiled.credentialIds,
            },
            connectedAt: new Date().toISOString(),
          },
        })
        .returning();

      return res.json({
        success: true,
        integration,
        platformWebhook,
        n8n: {
          workflowId: compiled.workflowId,
          workflowName: compiled.workflowName,
          webhookUrl: compiled.webhookUrl,
        },
      });
    } catch (error: any) {
      return res.status(500).json({ error: error.message || 'Failed to provision workflow' });
    }
  });

  return router;
}

