import { Router } from "express";
import adminCredentialsRoutes from "./admin-credentials-routes";
import adminNotificationsRoutes from "./admin-notifications-routes";
import adminKycRoutes from "./admin-kyc-routes";
import adminAuthRoutes from "./admin-auth-routes";
import adminPluginsRoutes from "./admin-plugins-routes";
import adminUsersRoutes from "./admin-users-routes";
import adminPhoneRoutes from "./admin-phone-routes";
import adminCallsRoutes from "./admin-calls-routes";
import adminCampaignsRoutes from "./admin-campaigns-routes";
import adminElevenLabsRoutes from "./admin-elevenlabs-routes";
import adminOpenaiRoutes from "./admin-openai-routes";
import adminLlmRoutes from "./admin-llm-routes";
import adminModerationRoutes from "./admin-moderation-routes";
import adminTemplatesRoutes from "./admin-templates-routes";
import adminBillingRoutes from "./admin-billing-routes";
import adminSettingsRoutes from "./admin-settings-routes";
import adminBrandingRoutes from "./admin-branding-routes";
import adminSeoRoutes from "./admin-seo-routes";
import adminAwsRoutes from "./admin-aws-routes";
import adminLanguagesRoutes from "./admin-languages-routes";
import adminIntegrationsRoutes from "./admin-integrations-routes";
import adminSipRoutes from "./admin-sip-routes";
import adminSupportRoutes from "./admin-support-routes";
import adminCatalogRoutes from "./admin-catalog-routes";
import adminInboundRoutes from "./admin-inbound-routes";
import adminKnowledgeRoutes from "./admin-knowledge-routes";
import adminStaffRoutes from "./admin-staff-routes";
import adminOperationsRoutes from "./admin-operations-routes";
import adminVoicesRoutes from "./admin-voices-routes";
import adminExternalContractRoutes from "./admin-external-contract-routes";
import adminSmsRatesRoutes from "./admin-sms-rates-routes";

const adminRouter = Router();

adminRouter.use(adminCatalogRoutes);
adminRouter.use(adminCredentialsRoutes);
adminRouter.use(adminNotificationsRoutes);
adminRouter.use(adminKycRoutes);
adminRouter.use(adminAuthRoutes);
adminRouter.use(adminPluginsRoutes);
adminRouter.use(adminUsersRoutes);
adminRouter.use(adminPhoneRoutes);
adminRouter.use(adminCallsRoutes);
adminRouter.use(adminCampaignsRoutes);
adminRouter.use(adminElevenLabsRoutes);
adminRouter.use(adminOpenaiRoutes);
adminRouter.use(adminLlmRoutes);
adminRouter.use(adminModerationRoutes);
adminRouter.use(adminTemplatesRoutes);
adminRouter.use(adminBillingRoutes);
adminRouter.use(adminSettingsRoutes);
adminRouter.use(adminBrandingRoutes);
adminRouter.use(adminSeoRoutes);
adminRouter.use(adminAwsRoutes);
adminRouter.use(adminLanguagesRoutes);
adminRouter.use(adminIntegrationsRoutes);
adminRouter.use(adminSipRoutes);
adminRouter.use(adminSupportRoutes);
adminRouter.use(adminInboundRoutes);
adminRouter.use(adminKnowledgeRoutes);
adminRouter.use(adminStaffRoutes);
adminRouter.use(adminOperationsRoutes);
adminRouter.use(adminVoicesRoutes);
adminRouter.use(adminExternalContractRoutes);
adminRouter.use(adminSmsRatesRoutes);

export default adminRouter;
