// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-layouts/CenteredOverlay.tsx": () => import("../components/mockups/login-layouts/CenteredOverlay.tsx"),
  "./components/mockups/login-layouts/HorizontalCompact.tsx": () => import("../components/mockups/login-layouts/HorizontalCompact.tsx"),
  "./components/mockups/login-layouts/StackedEditorial.tsx": () => import("../components/mockups/login-layouts/StackedEditorial.tsx")
};
