'use strict';

import { logger } from '../utils/logger';
import { getOpenAIClient } from './openai-modelfarm';
import { AWSBedrockService, BEDROCK_MODELS } from './aws-bedrock';
import type { InsertOpsTask } from '@shared/schema';

interface ExtractedTask {
  title: string;
  description: string;
  taskType: 'refund' | 'callback' | 'followup' | 'escalation' | 'other';
  priority: 'high' | 'medium' | 'low';
  intent: string;
  entities: Record<string, string | string[] | null>;
  sourceExcerpt: string;
}

export interface ComplianceViolation {
  description: string;
  category: 'missing_disclosure' | 'misleading_statement' | 'unauthorized_action' | 'identity_verification_failure';
  severity: 'critical' | 'major' | 'minor';
  evidence: string;
  recommendedCorrection: string;
}

export interface ComplianceReport {
  status: 'pass' | 'fail' | 'warning';
  violations: ComplianceViolation[];
}

export interface ExtractionResult {
  tasks: ExtractedTask[];
  callSummary: string;
  callBrief: CallBrief;
  complianceReport: ComplianceReport;
  provider: 'bedrock' | 'openai';
  modelUsed: string;
}

export interface CallBrief {
  headline: string;
  outcome: string;
  customerIntent: string;
  agentPerformance: string;
  followUpRequired: boolean;
  riskLevel: 'low' | 'medium' | 'high';
}

export interface BusinessContext {
  companyName?: string | null;
  agentSystemPrompt?: string | null;
  agentName?: string | null;
  departmentName?: string | null;
  language?: string | null;
  complianceRules?: {
    requiredPhrases?: string[];
    bannedPhrases?: string[];
    disclosures?: string[];
  } | null;
}

function buildSystemPrompt(businessContext?: BusinessContext): string {
  let businessSection = '';

  if (businessContext) {
    const lines: string[] = [];
    if (businessContext.companyName) {
      lines.push(`Company Name: ${businessContext.companyName}`);
    }
    if (businessContext.departmentName) {
      lines.push(`Department: ${businessContext.departmentName}`);
    }
    if (businessContext.agentName) {
      lines.push(`Agent Name: ${businessContext.agentName}`);
    }
    if (businessContext.language) {
      lines.push(`Primary Language: ${businessContext.language}`);
    }
    if (businessContext.agentSystemPrompt) {
      const truncatedPrompt = businessContext.agentSystemPrompt.substring(0, 2000);
      lines.push(`Agent Instructions (describes the business, products, and services):\n${truncatedPrompt}`);
    }
    if (businessContext.complianceRules) {
      const rules = businessContext.complianceRules;
      const ruleLines: string[] = [];
      if (rules.disclosures && rules.disclosures.length > 0) {
        ruleLines.push(`Required Disclosures (agent MUST say these during the call):\n${rules.disclosures.map(d => `  - "${d}"`).join('\n')}`);
      }
      if (rules.bannedPhrases && rules.bannedPhrases.length > 0) {
        ruleLines.push(`Banned Phrases (agent must NEVER say these):\n${rules.bannedPhrases.map(p => `  - "${p}"`).join('\n')}`);
      }
      if (rules.requiredPhrases && rules.requiredPhrases.length > 0) {
        ruleLines.push(`Required Phrases (agent MUST say these):\n${rules.requiredPhrases.map(p => `  - "${p}"`).join('\n')}`);
      }
      if (ruleLines.length > 0) {
        lines.push(`COMPLIANCE RULES:\n${ruleLines.join('\n')}`);
      }
    }
    if (lines.length > 0) {
      businessSection = `\n\nBUSINESS CONTEXT (use this to understand what this company does, what products/services they sell, and to correctly interpret the transcript):\n${lines.join('\n')}`;
    }
  }

  return `You are an expert operations analyst for an AI call center. Your job is to:
1. Extract structured, actionable follow-up tasks from call transcripts
2. Produce a concise call brief for the ops team
3. Assess risk level and whether follow-up is required
4. Perform a compliance audit identifying violations based on transcript evidence
5. ALL output (titles, descriptions, summaries, briefs) MUST be in English regardless of the transcript language
${businessSection}

Rules for task extraction:
1. Extract ALL tasks that require human follow-up action (refunds, callbacks, escalations, follow-ups, etc.)
2. CRITICAL: AI voice agents in call centers frequently say things like "I've registered your request", "I've submitted the form", "I've noted this", "I'll process this now", or provide generic reference numbers like REF12345, TKT-001, or any sequential-looking ID. These statements are SCRIPTED AGENT RESPONSES — they do NOT mean the action was actually performed in any real system. The ops team MUST still manually execute the action.
3. Reference numbers like REF12345, REF001, TKT-1234, #12345, or any placeholder-style ID generated by an AI agent during a call are NOT real confirmation numbers. Do NOT treat them as evidence of resolution.
4. A customer request is ONLY fully resolved when: the customer explicitly says they already received the refund/callback/service AND you see clear evidence from the transcript that a real system confirmed it (e.g., a payment gateway confirmation, not an agent's verbal statement).
5. MANDATORY RULE: If a customer requests a refund for ANY reason, ALWAYS create a "refund" type task, regardless of what the agent said during the call.
6. Each task must be specific and actionable
7. Classify task type as: refund, callback, followup, escalation, or other
8. Assign priority: high (refund/financial/urgent/angry customer), medium (standard follow-up), low (informational/optional)
9. Extract relevant entities (customer name, service name, amount, purchase date, account ID, order number, package name, product name, etc.)
10. Include the exact excerpt from the transcript that generated the task
11. Transcripts may be in Arabic, English, Hindi, Chinese, Spanish, French, or mixed languages — analyze all languages equally

CRITICAL RULE — STT Transcript Correction:
Speech-to-text (STT) transcripts from phone calls frequently contain garbled, mistranscribed, or phonetically-similar-but-wrong words, especially in Arabic and other non-English languages. You MUST use the BUSINESS CONTEXT above to correct and rationalize these errors. For example:
- If the business sells eSIM data packages and the transcript says "البقرة" (the cow), this is almost certainly a mistranscription of a product name, plan name, or technical term — interpret it in the business context, not literally.
- If a word makes no sense in the business context, infer the most likely intended meaning from phonetic similarity and context.
- NEVER produce task titles, descriptions, or summaries that contain nonsensical literal translations of STT errors. Always rationalize to what makes business sense.
- When quoting sourceExcerpt, you may include the original transcript text, but the title and description MUST reflect the corrected, business-rational interpretation.

IMPORTANT: Write ALL output fields (title, description, callSummary, callBrief headline/outcome/customerIntent/agentPerformance) in English. Even if the transcript is in Arabic or another language, the structured output must be in English for the ops team.

Rules for compliance audit:
1. Check for MISSING REQUIRED DISCLOSURES — if COMPLIANCE RULES list required disclosures or required phrases, verify whether the agent said them. If not, flag as "missing_disclosure".
2. Check for MISLEADING STATEMENTS — identify any incorrect or misleading claims made by the agent (e.g., promising something the business cannot deliver, quoting wrong prices, giving inaccurate information about policies).
3. Check for UNAUTHORIZED ACTIONS — identify actions the agent took or promised that they were not authorized to perform (e.g., approving refunds beyond limits, making commitments outside scope).
4. Check for IDENTITY VERIFICATION FAILURES — if the call involves sensitive account actions, check whether the agent properly verified the caller's identity before proceeding.
5. ONLY flag violations that are directly supported by transcript evidence — include the exact quote as evidence. Do NOT infer violations beyond what the transcript shows.
6. If COMPLIANCE RULES include banned phrases, check if the agent used any of them.
7. Assign severity: "critical" for serious regulatory/financial violations, "major" for significant policy breaches, "minor" for best-practice deviations.
8. Determine overall status: "pass" if no violations, "fail" if any critical or major violations exist, "warning" if only minor violations exist.

Always respond ONLY with valid JSON in this exact structure:
{
  "tasks": [
    {
      "title": "Brief action title (in English)",
      "description": "Detailed description of what needs to be done and why (in English)",
      "taskType": "refund|callback|followup|escalation|other",
      "priority": "high|medium|low",
      "intent": "The customer's underlying intent or need (in English)",
      "entities": { "customerName": "...", "orderId": "...", "amount": "...", "productName": "...", "packageName": "..." },
      "sourceExcerpt": "The exact quote from transcript that triggered this task"
    }
  ],
  "callSummary": "One paragraph summary of the call for ops team context (in English)",
  "callBrief": {
    "headline": "One sentence headline describing the call (in English, e.g. 'Customer inquired about Germany 10GB eSIM package activation')",
    "outcome": "resolved|escalated|pending|callback_scheduled|abandoned",
    "customerIntent": "What the customer wanted to achieve (in English)",
    "agentPerformance": "Brief assessment of how the agent handled the call (in English)",
    "followUpRequired": true,
    "riskLevel": "low|medium|high"
  },
  "complianceReport": {
    "status": "pass|fail|warning",
    "violations": [
      {
        "description": "What the violation is (in English)",
        "category": "missing_disclosure|misleading_statement|unauthorized_action|identity_verification_failure",
        "severity": "critical|major|minor",
        "evidence": "Exact transcript quote that proves this violation",
        "recommendedCorrection": "What the agent should have said or done instead (in English)"
      }
    ]
  }
}

If there are no actionable tasks, return empty tasks array. If there are no compliance violations, return complianceReport with status "pass" and empty violations array.
No markdown. No explanation. Only valid JSON.`;
}

const bedrock = new AWSBedrockService();

function buildUserMessage(
  transcript: string,
  callContext?: {
    aiSummary?: string | null;
    classification?: string | null;
    sentiment?: string | null;
    duration?: number | null;
    sessionOutcome?: string | null;
  }
): string {
  const contextLines = [
    callContext?.classification ? `Classification: ${callContext.classification}` : '',
    callContext?.sentiment ? `Sentiment: ${callContext.sentiment}` : '',
    callContext?.sessionOutcome ? `Session Outcome: ${callContext.sessionOutcome}` : '',
    callContext?.aiSummary ? `AI Summary: ${callContext.aiSummary}` : '',
  ].filter(Boolean);

  return [
    contextLines.length > 0 ? `CALL CONTEXT:\n${contextLines.join('\n')}` : '',
    `TRANSCRIPT:\n${transcript.substring(0, 12000)}`,
  ].filter(Boolean).join('\n\n');
}

function parseResult(raw: string): Omit<ExtractionResult, 'provider' | 'modelUsed'> {
  try {
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return emptyResult();
    const parsed = JSON.parse(jsonMatch[0]);
    return {
      tasks: Array.isArray(parsed.tasks) ? parsed.tasks : [],
      callSummary: parsed.callSummary || '',
      callBrief: parseBrief(parsed.callBrief),
      complianceReport: parseComplianceReport(parsed.complianceReport),
    };
  } catch {
    return emptyResult();
  }
}

function parseBrief(raw: unknown): CallBrief {
  if (!raw || typeof raw !== 'object') {
    return {
      headline: '',
      outcome: 'pending',
      customerIntent: '',
      agentPerformance: '',
      followUpRequired: false,
      riskLevel: 'low',
    };
  }
  const b = raw as Record<string, unknown>;
  return {
    headline: typeof b.headline === 'string' ? b.headline : '',
    outcome: typeof b.outcome === 'string' ? b.outcome : 'pending',
    customerIntent: typeof b.customerIntent === 'string' ? b.customerIntent : '',
    agentPerformance: typeof b.agentPerformance === 'string' ? b.agentPerformance : '',
    followUpRequired: typeof b.followUpRequired === 'boolean' ? b.followUpRequired : false,
    riskLevel: (['low', 'medium', 'high'].includes(b.riskLevel as string) ? b.riskLevel : 'low') as 'low' | 'medium' | 'high',
  };
}

function parseComplianceReport(raw: unknown): ComplianceReport {
  if (!raw || typeof raw !== 'object') {
    return { status: 'pass', violations: [] };
  }
  const r = raw as Record<string, unknown>;
  const validCategories = ['missing_disclosure', 'misleading_statement', 'unauthorized_action', 'identity_verification_failure'];
  const validSeverities = ['critical', 'major', 'minor'];

  const violations: ComplianceViolation[] = [];
  if (Array.isArray(r.violations)) {
    for (const v of r.violations) {
      if (v && typeof v === 'object') {
        const vObj = v as Record<string, unknown>;
        violations.push({
          description: typeof vObj.description === 'string' ? vObj.description : '',
          category: (validCategories.includes(vObj.category as string) ? vObj.category : 'missing_disclosure') as ComplianceViolation['category'],
          severity: (validSeverities.includes(vObj.severity as string) ? vObj.severity : 'minor') as ComplianceViolation['severity'],
          evidence: typeof vObj.evidence === 'string' ? vObj.evidence : '',
          recommendedCorrection: typeof vObj.recommendedCorrection === 'string' ? vObj.recommendedCorrection : '',
        });
      }
    }
  }

  let status: ComplianceReport['status'] = 'pass';
  if (violations.length > 0) {
    const hasCriticalOrMajor = violations.some(v => v.severity === 'critical' || v.severity === 'major');
    status = hasCriticalOrMajor ? 'fail' : 'warning';
  }

  return { status, violations };
}

function emptyResult(): Omit<ExtractionResult, 'provider' | 'modelUsed'> {
  return {
    tasks: [],
    callSummary: '',
    callBrief: {
      headline: '',
      outcome: 'pending',
      customerIntent: '',
      agentPerformance: '',
      followUpRequired: false,
      riskLevel: 'low',
    },
    complianceReport: { status: 'pass', violations: [] },
  };
}

function generateTrackingSerial(userId: string, callId: string, taskIndex: number): string {
  const now = new Date();
  const datePart = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`;
  const timePart = `${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;
  const userShort = userId.substring(0, 4).toUpperCase();
  const callShort = callId.substring(0, 6).toUpperCase();
  const seq = String(taskIndex + 1).padStart(2, '0');
  return `OPS-${datePart}-${timePart}-${userShort}-${callShort}-${seq}`;
}

async function extractWithBedrock(userMessage: string, systemPrompt: string): Promise<ExtractionResult> {
  const modelAlias = 'claude-sonnet-4-6';
  const modelId = BEDROCK_MODELS[modelAlias];

  logger.info('CallpilotAI: Using Bedrock Claude (primary)', { model: modelAlias }, 'CallpilotAI');

  const response = await bedrock.invoke({
    model: modelAlias,
    systemPrompt,
    messages: [{ role: 'user', content: userMessage }],
    maxTokens: 4000,
    temperature: 0.2,
  });

  const parsed = parseResult(response.content);
  return {
    ...parsed,
    provider: 'bedrock',
    modelUsed: modelId,
  };
}

async function extractWithOpenAI(userMessage: string, systemPrompt: string): Promise<ExtractionResult> {
  const model = 'gpt-4o';
  logger.info('CallpilotAI: Using OpenAI (fallback)', { model }, 'CallpilotAI');

  const openai = await getOpenAIClient();
  const response = await openai.chat.completions.create({
    model,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMessage },
    ],
    max_completion_tokens: 4000,
    temperature: 0.2,
  });

  const raw = response.choices[0]?.message?.content?.trim() || '{}';
  const parsed = parseResult(raw);
  return {
    ...parsed,
    provider: 'openai',
    modelUsed: model,
  };
}

export class CallpilotAI {
  static async extractTasksFromTranscript(
    transcript: string,
    callContext?: {
      aiSummary?: string | null;
      classification?: string | null;
      sentiment?: string | null;
      duration?: number | null;
      sessionOutcome?: string | null;
    },
    businessContext?: BusinessContext
  ): Promise<ExtractionResult> {
    const userMessage = buildUserMessage(transcript, callContext);
    const systemPrompt = buildSystemPrompt(businessContext);

    if (bedrock.isConfigured()) {
      try {
        return await extractWithBedrock(userMessage, systemPrompt);
      } catch (err: any) {
        logger.warn(
          'CallpilotAI: Bedrock failed, falling back to OpenAI',
          { error: err.message },
          'CallpilotAI'
        );
      }
    } else {
      logger.info('CallpilotAI: Bedrock not configured, using OpenAI directly', {}, 'CallpilotAI');
    }

    try {
      return await extractWithOpenAI(userMessage, systemPrompt);
    } catch (err: any) {
      logger.error('CallpilotAI: Both providers failed', { error: err.message }, 'CallpilotAI');
      return {
        ...emptyResult(),
        provider: 'openai',
        modelUsed: 'gpt-4o',
      };
    }
  }

  static buildInsertTasks(
    extracted: ExtractedTask[],
    userId: string,
    callId: string
  ): InsertOpsTask[] {
    return extracted.map((t, idx) => ({
      userId,
      callId,
      trackingSerial: generateTrackingSerial(userId, callId, idx),
      title: t.title,
      description: t.description,
      taskType: t.taskType,
      priority: t.priority,
      status: 'pending' as const,
      intent: t.intent,
      entities: t.entities,
      sourceExcerpt: t.sourceExcerpt,
      isDeleted: false,
    }));
  }
}
